// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIxn5DmE7cK4pfrQq8wWjhqVILKMmd2Oc',
    appId: '1:601191241341:web:fa49e783d1e1f392d20314',
    messagingSenderId: '601191241341',
    projectId: 'flutter-notification-befbf',
    authDomain: 'flutter-notification-befbf.firebaseapp.com',
    storageBucket: 'flutter-notification-befbf.appspot.com',
    measurementId: 'G-5QSGF9FF6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKs9MjFN9qZMbakXUpUN80Dg1JyVfh-dI',
    appId: '1:601191241341:android:8e9bfef1308cb0dbd20314',
    messagingSenderId: '601191241341',
    projectId: 'flutter-notification-befbf',
    storageBucket: 'flutter-notification-befbf.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIxn5DmE7cK4pfrQq8wWjhqVILKMmd2Oc',
    appId: '1:601191241341:web:fbe464335e6a5c1dd20314',
    messagingSenderId: '601191241341',
    projectId: 'flutter-notification-befbf',
    authDomain: 'flutter-notification-befbf.firebaseapp.com',
    storageBucket: 'flutter-notification-befbf.appspot.com',
    measurementId: 'G-4S3L7EJF0D',
  );
}
